### ISSUE TITLE
Image Generator: Out Of Range Exception if Eternal difficulty scores are present in the request JSON

### ISSUE THREAD

**Issue by JustVldKsh** [ArcaeaOffline/client-pyside6#13]
In short, basically title, just tried to test B30 generation and figured out it didn't work possibly because of Eternal difficulty scores being present in the request, reporting here since unable to report towards your fork of Andreal Image Generator

### Longer explanation:

Were testing some things under Windows (alongside doing some chores like updating my db) and decided to test B30 generation

Wanted to report to the repo of your fork of the image generator, but saw it has issues disabled

First it shows this error if you try to generate a preview or the image inside Arcaea Offline
```
Invalid base64-encoded string: number of data characters (25) cannot be 1 more than a multiple of 4
```

Afterwards I tried exporting request JSON to test if CLI works, but got this error instead
```
Error: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
Try `--help` for more information.
Unhandled exception. System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at AndrealImageGenerator.Beans.RecordInfo..ctor(ArcSongdata recentdata) in D:\develop\283375\AndrealImageGenerator\Beans\RecordInfo.cs:line 15
   at AndrealImageGenerator.Beans.Best40Data.<>c.<get_Best30List>b__9_0(ArcSongdata i) in D:\develop\283375\AndrealImageGenerator\Beans\Best40Data.cs:line 18
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AndrealImageGenerator.Beans.Best40Data.get_Best30List() in D:\develop\283375\AndrealImageGenerator\Beans\Best40Data.cs:line 18
   at AndrealImageGenerator.Graphics.Generators.Best40Generator.Generate() in D:\develop\283375\AndrealImageGenerator\Graphics\Generators\Best40Generator.cs:line 22
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AndrealImageGenerator.Api.Api.GetUserBest30(String jsonStr, Int32 imgVersion) in D:\develop\283375\AndrealImageGenerator\Api.cs:line 83
   at Program.<Main>$(String[] args) in D:\develop\283375\AndrealImageGenerator\Program.cs:line 68
```

After which I thought it might be Eternal difficulty potentially being unsupported (since it was added just back in march), copied the database and removed all scores on Eternal charts from it, which worked and I was able to generate B30 images

**Comment by 283375** [comment]
Actually I do have a refactoring plan of this *Andreal Image Generator* on my to-do list, but it's not a high priority right now, since the source program is a fork and I'm not very familiar with C#.
I'll probably check back late this August, depends on how much time I've got.

> Wanted to report to the repo of your fork of the image generator, but saw it has issues disabled

Looks like I've forgot to enable some options after I forked it... or maybe I did disable it, but I can't really remember
Anyway the issues section should appear now, you may open a new one if you find any other bugs.

**Comment by JustVldKsh** [comment]
Can understand, not familiar with C# myself, but so far I don't think there's any more issues at the moment (other than non-b30 modes requiring a bit of extra config/whatever work)

But I think I could try poking around myself and try adding Eternal support later, especially since the error seems to point at where to look, and it looks like a quick enough fix, other than setting up the C# dev environment
